### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by mgoeller** [TinkeringAround/HomeKit-Website#7]
Is this a front-end to control HomeKit accessories? How does the pairing with the accessories work?

**Comment by TinkeringAround** [comment]
I build my accessories myself using an ESP8266 and the FirebaseArduino Library, which are registering themself at my Firebase Project. This is just the Frontend for retrieving these information. I do not intend to use the "overpriced" official HomeKit products for Apples HomeKit. :D

Greetings

**Comment by mgoeller** [comment]
Thanks. Why don't you use the library from Maxim Kulkin directly for your ESP based Accessories? https://github.com/maximkulkin/esp-homekit
